9 sprint for review
TerentevOleg/java-filmorate pull request #1
Opened 2022-09-08 15:03 UTC by Olegenchi

2022-09-09 20:06 UTC, alexache requested changes

2022-09-09 20:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> filmList = new HashMap<>();
Опционально - не стоит использовать слова map, list, set в названии переменных, слишком часто придется переименовывать :)

2022-09-09 20:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private LocalDate MIN_DATE = LocalDate.of(1895, 12, 28);
Можно и final сразу сделать

2022-09-09 20:06 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Дата релиза не может быть раньше 28.12.1895 г.");
Какое-то дублирование проверок-валидаций. Если с датой что-то не так, то уже будет эксепшен ниже

2022-09-09 20:06 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
Тесты огонь, очень подробные, круто!

2022-09-09 21:44 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Integer, Film> filmList = new HashMap<>();
Исправлено

2022-09-09 21:44 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private LocalDate MIN_DATE = LocalDate.of(1895, 12, 28);
Исправлено

2022-09-09 21:45 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Дата релиза не может быть раньше 28.12.1895 г.");
Исправлено

2022-09-09 21:45 UTC, Olegenchi commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
Спасибо!

2022-09-10 05:38 UTC, alexache approved these changes

2022-09-14 14:01 UTC, merged