Add friends likes
TerentevOleg/java-filmorate pull request #2
Opened 2022-09-27 14:37 UTC by Olegenchi

2022-09-28 19:23 UTC, alexache requested changes

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmValidator.java
> +    private final InMemoryFilmStorage filmStorage;
Должны использовать интерфейс вместо конкретной реализации

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +@Data
Для чего это аннотация здесь?

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +    private final InMemoryUserStorage userStorage;
Контроллер должен взаимодействовать только с сервисом, который уже будет взаимодействовать со стораджем

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +    private final InMemoryFilmStorage filmStorage;
Желательно. чтобы со стораджами работали только сервисы, а контроллеры взаимодействовал с ними, иначе нарушается принцип single responsibility

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +@Data
Для чего эта аннотация?

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Должны использоваться интерфейсы, а не конкретные реализации

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage userStorage;
Должны использоваться интерфейсы, а не конкретные реализации

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getAllFilms().get(filmId);
Это как-то неоптимально, лучше завести метод получения фильма по айди на самом сторадже, чем каждый раз делать такие обходы и завязываться на индекс фильма в листе

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getAllUsers().get(userId);
Это как-то неоптимально, лучше завести метод получения юзера по айди на самом сторадже, чем каждый раз делать такие обходы и завязываться на индекс юзера в листе

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
К тому же, что будет, если нет фильма с таким айди? NullPointerException?

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +@Data
Для чего эта аннотация?

2022-09-28 19:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
>  @Data
Это как-то неоптимально, лучше завести метод получениф фильма по айди на самом сторадже, чем каждый раз делать такие обходы и завязываться на индекс фильма в листе

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmValidator.java
> +    private final InMemoryFilmStorage filmStorage;
Исправлено

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +@Data
Удалены лишние аннотации

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserController.java
> +    private final InMemoryUserStorage userStorage;
Исправлено

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +    private final InMemoryFilmStorage filmStorage;
Исправлено

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmController.java
> +@Data
Удалены лишние аннотации

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final InMemoryFilmStorage filmStorage;
Исправлено

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final InMemoryUserStorage userStorage;
Исправлено

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getAllFilms().get(filmId);
Метод получения фильма по id перенесен в сторадж

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return userStorage.getAllUsers().get(userId);
Метод получения юзера по id перенесен в сторадж

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    }
Добавлена проверка на нулл в юзер и фильм валидацию

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +@Data
Лишняя аннотация удалена

2022-10-01 15:01 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
>  @Data
Исправлено

2022-10-01 19:28 UTC, alexache approved these changes

2022-10-01 19:28 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmValidator.java
> +        if (filmService.getFilmById(filmId) == null) {
filmService.getFilmById(filmId) лучше сразу сохранить в переменную, чтобы не делать жту операцию получения по айди многократно

2022-10-01 19:28 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmValidator.java
> +        if (!filmService.findAllFilms().contains(filmService.getFilmById(filmId))) {
Не очень понятная проверка и для чего она, берем объект из этого списка и снова ищем его среди списка всех фильмов по equals

2022-10-01 19:28 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserValidator.java
> +        if (!userService.findAllUsers().contains(userService.getUserById(userId))) {
Такой же комментарий, как и фильмов - не очень понятная проверка

2022-10-01 21:14 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmValidator.java
> +        if (!filmService.findAllFilms().contains(filmService.getFilmById(filmId))) {
Исправлено

2022-10-01 21:14 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/user/UserValidator.java
> +        if (!userService.findAllUsers().contains(userService.getUserById(userId))) {
Исправлено

2022-10-01 21:15 UTC, Olegenchi commented on src/main/java/ru/yandex/practicum/filmorate/controller/film/FilmValidator.java
> +        if (filmService.getFilmById(filmId) == null) {
Исправил след замечания, поэтому вызов по айди в методе получается один раз

2022-10-01 21:17 UTC, merged