Add database
TerentevOleg/java-filmorate pull request #3
Opened 2022-10-20 19:14 UTC by TerentevOleg

2022-10-22 06:08 UTC, alexache requested changes

2022-10-22 06:08 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmDbStorage filmDbStorage;
Должен использоваться интерфейс. а не конкретная реализация

2022-10-22 06:08 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final UserDbStorage userDbStorage;
Должен использоваться интерфейс. а не конкретная реализация

2022-10-22 06:08 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/StorageDbCommon.java
> +public class StorageDbCommon {
Для чего это выносить в отдельный класс? Разве нет соответствующих LikeDbStorage/GenreDbStorage и т.д.?

2022-10-22 06:08 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/RowMapper.java
> +public class RowMapper {
Это тоже можно было бы сделать частью соответствующих DbStorage, чтобы все, относящееся к хранению сущности, было в классе-сторадже этой сущности

2022-10-22 06:08 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/StorageDbCommon.java
> +        films.forEach(this::setMpaName);
Не очень понятно, эта информацию уже есть благодаря селекту с джоином. зачем еще раз делать запросы к базе?

2022-10-22 06:08 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/StorageDbCommon.java
> +        films.forEach(this::setLike);
Такие запросе очень плохо делать циклом по каждому элементу списка фильмов. Каждый отдельный запрос - это затратная операция - больше запросов - хуже производительность. Этим мог бы заниматься сервис - вызывать сторадж жанров, чтобы одним запросом получить все жанры для списка фильмов

2022-10-22 19:27 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmDbStorage filmDbStorage;
Исправлено

2022-10-22 19:27 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final UserDbStorage userDbStorage;
Исправлено

2022-10-22 19:27 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/storage/StorageDbCommon.java
> +public class StorageDbCommon {
Исправлено

2022-10-22 19:27 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/storage/RowMapper.java
> +public class RowMapper {
Исправлено

2022-10-22 19:27 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/storage/StorageDbCommon.java
> +        films.forEach(this::setMpaName);
Исправлено

2022-10-22 19:27 UTC, TerentevOleg commented on src/main/java/ru/yandex/practicum/filmorate/storage/StorageDbCommon.java
> +        films.forEach(this::setLike);
Исправлено

2022-10-24 07:31 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/StorageDbCommon.java
> +        films.forEach(this::setLike);
В этом есть минус. Для всего списка фильмов можно получать все жанры одним запросом по типу с select from .. where film_id in (..)
Еще немного смущается, что часть "насыщения" жанрами сделаны прямо в репозитории, а часть в сервисе. В сервисе будет лучше

2022-10-24 07:31 UTC, alexache approved these changes

2022-10-26 19:41 UTC, merged